Bravissimo/Controllers/LanguageController.cs
using Bravissimo.Models;
using Bravissimo.Repositories;
using Bravissimo.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Bravissimo.Controllers
{
    public class LanguageController : Controller
    {
        private readonly ILanguageRepository _languageRepository;

        public LanguageController(ILanguageRepository languageRepository)
        {
            _languageRepository = languageRepository;
        }

        public IActionResult Index()
        {
            List<Language> objList = _languageRepository.GetLanguageList();
            
            if (objList == null)
                return NotFound();

            var vm = new LanguageViewModel() { LanguageList = objList };

            return View(vm);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AddEditLanguageViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var obj = new Language()
                {
                    ID = vm.ID,
                    Name = vm.Name,
                    IsVisible = vm.IsVisible,
                    IsSrcAllowed = vm.IsSrcAllowed,
                    IsDstAllowed = vm.IsDstAllowed
                };

                try
                {
                    _languageRepository.AddLanguage(obj);
                }
                catch (Exception ex) 
                {
                    //ERROR ADDING LANGUAGE ERROR;
                }

                return RedirectToAction("Index");
            }
            return View(vm);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();

            var obj = _languageRepository.GetLanguageById(Id);

            if (obj == null)
                return NotFound();

            var vm = new AddEditLanguageViewModel()
            {
                ID = obj.ID,
                IsDstAllowed = obj.IsDstAllowed,
                IsSrcAllowed = obj.IsSrcAllowed,
                IsVisible = obj.IsVisible,
                Name = obj.Name
            };

            if (obj == null)
                return NotFound();

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AddEditLanguageViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var obj = new Language()
                {
                    ID = vm.ID,
                    Name = vm.Name,
                    IsDstAllowed = vm.IsDstAllowed,
                    IsSrcAllowed = vm.IsSrcAllowed,
                    IsVisible = vm.IsVisible
                };

                try
                {
                    _languageRepository.UpdateLanguage(obj);
                }
                catch (Exception ex) 
                {
                    //ERROR UPDATE LANGUAGE;
                }

                return RedirectToAction("Index");
            }
            return View(vm);
        }

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();

            var obj = _languageRepository.GetLanguageById(Id);

            if (obj == null)
                return NotFound();

            var vm = new AddEditLanguageViewModel()
            {
                ID = obj.ID,
                Name = obj.Name,
                IsVisible = obj.IsVisible,
                IsSrcAllowed = obj.IsSrcAllowed,
                IsDstAllowed = obj.IsDstAllowed
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            var obj = _languageRepository.GetLanguageById(Id);
            if (obj == null)
                return NotFound();

            try
            {
                _languageRepository.DeleteLanguage(obj);
            }
            catch (Exception ex) 
            {
                //ERROR DELETING LANGUAGE;
            }

            return RedirectToAction("Index");
        }
    }
}

Bravissimo/Controllers/RequestController.cs
using Bravissimo.Models;
using Bravissimo.Repositories;
using Bravissimo.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Bravissimo.Controllers
{
    public class RequestController : Controller
    {
        private readonly IRequestRepository _requestRepository;
        private readonly ILanguageRepository _languageRepository;

        public RequestController( IRequestRepository requestRepository, ILanguageRepository languageRepository)
        { 
            _requestRepository = requestRepository;
            _languageRepository = languageRepository;
        }

        public IActionResult Index(string status)
        {
            if (status == null)
            {
                status = "primljeni";
            }

            List<Request> objList = _requestRepository.GetRequestList().Where(s => s.Status == status).ToList();

            if (objList == null)
                return NotFound();
 
            var vm = new RequestViewModel() { RequestList = objList };
            vm.status = status;
            return View(vm);
        }

        public IActionResult Edit(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();

            var obj = _requestRepository.GetRequestById(Id);
            var languages = _languageRepository.GetLanguageList();

            if (obj == null)
                return NotFound();

            var vm = new EditRequestViewModel()
            {
                ID = obj.ID,
                ReceivedDate = obj.ReceivedDate,
                SentBy = obj.SentBy,
                SrcLangId = obj.SrcLang.ID,
                DstLangId = obj.DstLang.ID,
                SrcLang = obj.SrcLang,
                DstLang = obj.DstLang,
                Deadline = obj.Deadline,
                ResponseDate = obj.ResponseDate,
                RespondedBy = obj.RespondedBy,
                ResponseMessage = obj.ResponseMessage,
                Price = obj.Price,
                Language = languages
            };

            if (obj == null)
                return NotFound();

            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditRequestViewModel vm)
        {

            if (ModelState.IsValid)
            {
                var obj = new Request()
                {
                    ID = vm.ID,
                    ReceivedDate = vm.ReceivedDate,
                    SentBy = vm.SentBy,
                    Deadline = vm.Deadline,
                    ResponseDate = vm.ResponseDate,
                    RespondedBy = vm.RespondedBy,
                    ResponseMessage = vm.ResponseMessage,
                    Price = vm.Price,
                    Status = "odgovoreni"
                };

                obj.DstLang = _languageRepository.GetLanguageById(vm.DstLangId);
                obj.SrcLang = _languageRepository.GetLanguageById(vm.SrcLangId);

                try
                {
                    _requestRepository.UpdateRequest(obj);
                }
                catch (Exception ex)
                {
                    //ERROR UPDATE LANGUAGE;
                }

                return RedirectToAction("Index");
            }
            return View(vm);
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();

            var obj = _requestRepository.GetRequestById(Id);

            if (obj == null)
                return NotFound();

            var vm = new EditRequestViewModel()
            {
                ID = obj.ID,
                ReceivedDate = obj.ReceivedDate,
                SentBy = obj.SentBy,
                SrcLang = obj.SrcLang,
                DstLang = obj.DstLang,
                Deadline = obj.Deadline,
                ResponseDate = obj.ResponseDate,
                RespondedBy = obj.RespondedBy,
                ResponseMessage = obj.ResponseMessage,
                Price = obj.Price
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? Id)
        {
            var obj = _requestRepository.GetRequestById(Id);
            if (obj == null)
                return NotFound();

            try
            {
                _requestRepository.DeleteRequest(obj);
            }
            catch (Exception ex)
            {
                //ERROR DELETING LANGUAGE;
            }

            return RedirectToAction("Index");
        }

        //[HttpPost]
        //public ActionResult FilterByStatus (string status)
        //{
        //    return RedirectToAction("Index", new { status = status});
        //}
    }
}

Bravissimo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bravissimo</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bravissimo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bravissimo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>